### ISSUE TITLE
Ability to choose the color of the bakground for website prediction?

### ISSUE THREAD

**Issue by 1ll3g4l** [spikespaz/firefox-nativedark#25]
<img src='https://i.imgur.com/6hGUw84.png'/>

Anyway to make it white? i remember it being white before as well.

**Comment by spikespaz** [comment]
Firefox version 60 was released, and therefore popups such as this may be colored. This is intentional behavior. However I may be able to add an option in the rewrite.

**Comment by spikespaz** [comment]
See Issue #7

**Comment by Keith94** [comment]
Ooh. that's good news; when can we expect the rewrite? :D 

@1ll3g4l In the meantime you can customize this with userChrome.css

```css
.autocomplete-richlistitem[selected] {
  background: #FFFFFF !important;
}
```
